/* Reviewed replacements for the earlier fixed storyboards. Old versions remain available. */
{
const R=(id,label,min,max,value,step=1)=>({id,label,type:'range',min,max,step,value});
const S=(id,label,options,value)=>({id,label,type:'select',options:options.map(([value,label])=>({value,label})),value});
const f=(svg,note,values)=>({svg,note,values}),one=(svg,note,values)=>({frames:[f(svg,note,values)]});
const seq=(n,g)=>Array.from({length:n},(_,i)=>g(i)),sum=a=>a.reduce((s,x)=>s+x,0),round=x=>+x.toFixed(4);
const curve=(fn,a,b)=>seq(101,i=>{const x=a+(b-a)*i/100;return[x,fn(x)]});
const add=(id,session,title,question,controls,scope,takeaway,compute)=>register({id,version:'2.0.0',session,title,question,description:question,controls,scope,takeaway,compute});

add('hub-functions','math-functions.c2.s2','函数变换：移动谁、缩放谁？','f(x−a)+b 里的减号为什么让图像向右？',[R('a','水平位移 a',-3,3,1,.25),R('b','垂直位移 b',-3,3,0,.25)],'抛物线 y=x² 与 y=(x−a)²+b；顶点和平移同时显示。','要取得原来的函数值，输入必须补回 a，所以 x−a 对应向右平移。',p=>one(Viz.plot({series:[{points:curve(x=>x*x,-4,4),label:'原函数 x²'},{points:curve(x=>(x-p.a)**2+p.b,-4,4),label:'变换后'}],points:[[0,0],[p.a,p.b]],segments:[[0,0,p.a,p.b]],xDomain:[-4,4],yDomain:[-4,12]}),`顶点从 (0,0) 移到 (${p.a},${p.b})；将 a 改成负数检验移动方向。`,{vertex:[p.a,p.b],valueAtZero:p.a*p.a+p.b}));
add('hub-derivative','math-calculus.c1.s2','割线如何靠近切线','差商里的两个点靠近时，斜率怎样变化？',[R('x','切点 x',-2,2,1,.1),R('h','两点间隔 h',.01,1.5,.6,.01)],'y=x²；差商=2x+h，解析导数=2x。','割线有两个点，切线描述一个点处的局部变化；h 必须趋零而不是直接把分母设为零。',p=>one(Viz.plot({series:[{points:curve(x=>x*x,-3,4),label:'y=x²'},{points:curve(x=>2*p.x*(x-p.x)+p.x*p.x,p.x-1,p.x+1),label:'切线'}],segments:[[p.x,p.x*p.x,p.x+p.h,(p.x+p.h)**2]],points:[[p.x,p.x*p.x],[p.x+p.h,(p.x+p.h)**2]],xDomain:[-3,4],yDomain:[-1,17]}),`割线斜率 ${round(2*p.x+p.h)}，切线斜率 ${round(2*p.x)}，两者相差 h=${p.h}。`,{secant:2*p.x+p.h,derivative:2*p.x,error:p.h}));
add('hub-linear','math-linear.c2.s1','两个基向量怎样改变整个平面','剪切和缩放分别怎样改变网格？',[R('shear','水平剪切 k',-2,2,1,.25),R('scale','竖直缩放 s',-1,2,1,.25)],'矩阵 [[1,k],[0,s]]；包含 s=0 的降维与负行列式的翻转。','基向量决定整个线性映射；行列式为零时，整个平面会压到一条线。',p=>{const T=([x,y])=>[x+p.shear*y,p.scale*y],segments=[];for(let i=-2;i<=2;i++){segments.push([...T([i,-2]),...T([i,2])],[...T([-2,i]),...T([2,i])]);}return one(Viz.plot({equalAspect:true,segments,points:[T([1,0]),T([0,1])],xDomain:[-6,6],yDomain:[-5,5],xLabel:'变换后的横坐标',yLabel:'变换后的纵坐标'}),`e₁→(1,0)，e₂→(${p.shear},${p.scale})；有向面积倍率 det(A)=${p.scale}。${p.scale===0?'此时丢失一个维度。':''}`,{basis:[T([1,0]),T([0,1])],determinant:p.scale});});
add('hub-bayes','math-probability.c1.s2','贝叶斯：阳性里有多少真阳性','检测性能不变，低基率为什么带来更多误报？',[R('base','基率 %',1,50,5),R('falsePositive','假阳性率 %',1,30,10)],'每1000人的期望人数，灵敏度固定90%；教学概率模型，不用于医学判断。','后验需要同时比较真阳性与假阳性，不能只读取灵敏度。',p=>{const diseased=p.base*10,tp=diseased*.9,fp=(1000-diseased)*p.falsePositive/100,posterior=tp/(tp+fp);return one(Viz.bars([tp,fp],['真阳性','假阳性'],[0]),`阳性共 ${round(tp+fp)} 人，其中真阳性 ${round(tp)} 人；后验 = ${round(tp)} ÷ ${round(tp+fp)} = ${round(posterior*100)}%。`,{truePositive:tp,falsePositive:fp,posterior});});
add('probability.density.area','math-probability.c2.s1','密度高度与区间概率','密度高于1，概率就违反规则了吗？',[R('width','均匀分布宽度',.25,4,1,.25),R('portion','观察区间占比 %',10,100,50,10)],'均匀分布支持集[0,w]；观察区间[0,w·占比]。','概率是面积；缩窄支持集会提高密度，但总面积仍为1。',p=>{const probability=p.portion/100,part=p.width*probability;return one(Viz.plot({series:[{points:[[0,0],[0,1/p.width],[p.width,1/p.width],[p.width,0]],label:'密度'}],segments:[[0,1/p.width,part,1/p.width]],xDomain:[0,4],yDomain:[0,4.2],xLabel:'取值',yLabel:'密度'}),`密度 ${round(1/p.width)}，观察宽度 ${round(part)}，概率=高度×宽度=${probability}。`,{density:1/p.width,intervalWidth:part,probability,totalArea:1});});
add('data_structures.linked_list.insert','data-structures.c1.s1','链表插入：先接后断','两次指针赋值换个顺序，原后继还找得到吗？',[S('order','赋值顺序',[['safe','先 new.next = old.next'],['bad','先 old.next = new']],'safe'),R('value','新节点值',2,9,5)],'在 A→B 中插入 N；没有另存 B 指针时，错误顺序会丢失原链并产生自环。','修改唯一引用以前先保存原后继，才能保持整条链可达。',p=>{let next={A:'B',N:null,B:null};const nodes=[{id:'A',label:'A:1'},{id:'N',label:'N:'+p.value},{id:'B',label:'B:10'}];const frame=note=>f(Viz.graph({nodes,edges:Object.entries(next).filter(([,v])=>v).map(([a,b])=>({from:a,to:b,label:'next'})),layout:'tree',directed:true}),note,{next:{...next},lost:next.A==='N'&&next.N!=='B'});const frames=[frame('初始：A 指向 B，新节点 N 尚未接入。')];if(p.order==='safe'){next.N=next.A;frames.push(frame('先把 N.next 指向 B，原后继被保留。'));next.A='N';frames.push(frame('再把 A.next 改成 N，得到 A→N→B。'));}else{next.A='N';frames.push(frame('A.next 被覆盖，B 已不能从 A 找到。'));next.N=next.A;frames.push(frame('再读 A.next 得到的是 N，自环形成；原 B 丢失。'));}return{frames};});
add('networking.tcp.handshake','networks.c2.s1','TCP：双方怎样确认收发能力','丢掉握手中的一个包，会让哪一方停在哪个状态？',[S('lost','丢失消息',[['none','不丢包'],['syn','第1个 SYN'],['synack','第2个 SYN+ACK'],['ack','第3个 ACK']],'none'),R('isn','客户端初始序号',10,90,40,10)],'展示首次握手尝试；不模拟重传计时、数据携带与 SYN cookie；SYN 占一个序号。','双方各自维护连接状态；客户端认为连接建立时，服务端仍可能等待最后确认。',p=>{let states=['CLOSED','LISTEN'];const frames=[];function emit(note,msg='',from=0){let body=Viz.text(140,25,'客户端',14)+Viz.text(460,25,'服务端',14)+Viz.line(140,42,140,220)+Viz.line(460,42,460,220)+Viz.text(140,258,states[0],12)+Viz.text(460,258,states[1],12);if(msg)body+=Viz.line(from?448:152,120,from?152:448,120,Viz.colors[1])+Viz.text(300,103,msg,12)+Viz.text(from?157:443,126,from?'‹':'›',22);frames.push(f(Viz.svg(body,600,280),note,{client:states[0],server:states[1]}));}emit('双方最初还未建立连接。');states[0]='SYN-SENT';emit('客户端发送 SYN，发出自己的初始序号。','SYN seq='+p.isn);if(p.lost==='syn'){emit('SYN 丢失，服务端仍在监听；等待重传。');return{frames};}states[1]='SYN-RECEIVED';emit('服务端确认客户端序号，并发送自己的 SYN。',`SYN+ACK seq=100, ack=${p.isn+1}`,1);if(p.lost==='synack'){emit('第二条消息丢失，双方分别等待重传与响应。');return{frames};}states[0]='ESTABLISHED';emit('客户端收到确认，发送 ACK。','ACK seq='+(p.isn+1)+', ack=101');if(p.lost==='ack'){emit('最后 ACK 丢失：客户端已建立，服务端仍等待；状态暂时不一致。');return{frames};}states[1]='ESTABLISHED';emit('服务端收到最后确认，双方都已建立连接。');return{frames};});
add('networking.dns.resolution','networks.c3.s1','DNS：缓存把哪几段查询省掉了','过期缓存与有效缓存，会走同一条路径吗？',[S('cache','缓存位置',[['none','全部未命中'],['client','客户端有效缓存'],['resolver','递归器有效缓存']],'none'),S('answer','权威返回',[['ok','存在 A 记录'],['missing','域名不存在']],'ok')],'一个域名的教学查询；有效正向缓存优先返回，权威变化在缓存过期后才可见；不模拟 DNSSEC 与 CNAME。','客户端问递归器取得最终结果，递归器向不同权威服务器逐级寻找答案。',p=>{const labels=['客户端','递归解析器','根服务器','顶级域服务器','权威服务器'],edges=[],frames=[];const push=(a,b,note)=>{if(a!==null)edges.push({from:String(a),to:String(b),label:edges.length+1+''});frames.push(f(Viz.graph({nodes:labels.map((label,i)=>({id:String(i),label,active:i===b})),edges,directed:true,layout:'circle'}),note,{messageCount:edges.length,result:note}));};if(p.cache==='client'){push(null,0,'客户端的有效正向缓存直接返回 IP，不发起网络查询。');return{frames};}push(0,1,'客户端请求递归解析器。');if(p.cache==='resolver'){push(1,0,'递归器的有效缓存直接返回 IP。');return{frames};}push(1,2,'询问根服务器，获得顶级域服务器线索。');push(1,3,'询问顶级域服务器，获得权威服务器线索。');push(1,4,'权威服务器给出最终记录或 NXDOMAIN。');push(1,0,p.answer==='ok'?'递归器缓存并返回 A 记录。':'递归器返回 NXDOMAIN；否定结果也可按规则缓存。');return{frames};});
add('database.transaction.dirty_read','databases.c2.s1','事务隔离：读到的余额会消失吗','写入尚未提交时，另一个事务能否看见？',[S('level','读隔离',[['uncommitted','读未提交'],['committed','读已提交（快照示意）']],'uncommitted'),S('finish','写事务结局',[['rollback','回滚'],['commit','提交']],'rollback')],'初始余额100，T1暂写60；读已提交使用已提交版本示意，具体数据库也可能阻塞。','脏读的判据是读了尚未提交的数据；后来是否回滚不是定义的必要条件。',p=>{const read=p.level==='uncommitted'?60:100,final=p.finish==='commit'?60:100;return{frames:[f(Viz.cells([100,'—','—'],{labels:['已提交余额','T1暂写','T2读取']}),'初始余额100。',{committed:100}),f(Viz.cells([100,60,'—'],{active:[1],labels:['已提交余额','T1暂写','T2读取']}),'T1 写入60，尚未提交。',{committed:100,uncommitted:60}),f(Viz.cells([100,60,read],{active:[2],labels:['已提交余额','T1暂写','T2读取']}),`T2 读到${read}；${p.level==='uncommitted'?'这是未提交版本，构成脏读。':'只读取已提交版本100。'}`,{read,dirty:p.level==='uncommitted'}),f(Viz.cells([final,read],{labels:['最终余额','T2曾经读取']}),`T1 ${p.finish==='commit'?'提交':'回滚'}，最终余额${final}；T2 曾读到${read}。`,{final,read,dirty:p.level==='uncommitted'})]};});

function heatmap(a,x,y,cell,active=[],title='',scale){let b=Viz.text(x+cell*a[0].length/2,y-12,title,13);const max=scale||Math.max(1,...a.flat().map(Math.abs));a.forEach((row,r)=>row.forEach((v,c)=>{if(v===null){b+=Viz.rect(x+c*cell,y+r*cell,cell-1,cell-1,'#fff','#d8e1dd');return;}const color=v<0?'#d57a19':'#087f8c';b+=`<rect x="${x+c*cell}" y="${y+r*cell}" width="${cell-1}" height="${cell-1}" rx="2" fill="${color}" fill-opacity="${.08+.85*Math.abs(v)/max}" stroke="${active.includes(r*a[0].length+c)?'#d57a19':'none'}" stroke-width="2"/>`;}));return b;}
add('deep_learning.cnn.mechanism','deep-learning.c2.s1','CNN：从笔画到特征与分类','一个局部窗口怎样逐步变成分类分数？',[S('digit','输入笔画',[['7','数字7'],['1','数字1'],['0','数字0（范围外反例）']],'7'),R('shift','水平移动',-1,1,0)],'8×8合成笔画；两个3×3手工核、ReLU、2×2最大池化、全局平均与手工二分类头。未训练，不代表MNIST识别准确率；0是二分类范围外反例。','卷积共享局部权重，分类仍依赖学到或设定的特征与决策边界；Softmax不能保证正确识别。',p=>{const a=seq(8,()=>Array(8).fill(0));for(let r=1;r<7;r++)for(let c=1;c<7;c++){let on=p.digit==='7'?(r===1||c===7-r):p.digit==='1'?c===4:(r===1||r===6||c===1||c===6);const col=c+p.shift;if(on&&col>=0&&col<8)a[r][col]=1;}const kernels=[[[0,0,0],[1,1,1],[-1,-1,-1]],[[0,0,1],[0,1,0],[1,0,0]]],maps=kernels.map(()=>seq(6,()=>Array(6).fill(null))),frames=[];frames.push(f(Viz.svg(heatmap(a,210,46,25,[],'输入：8×8像素'),600,275),'亮格组成输入笔画。按下一步，观察同一个卷积核如何扫过不同位置。',{input:a}));for(let k=0;k<2;k++){for(let r=0;r<6;r++)for(let c=0;c<6;c++){let v=0;for(let i=0;i<3;i++)for(let j=0;j<3;j++)v+=a[r+i][c+j]*kernels[k][i][j];maps[k][r][c]=v;if((r*6+c)%5===0||r*6+c===35){const active=seq(9,i=>(r+Math.floor(i/3))*8+c+i%3);frames.push(f(Viz.svg(heatmap(a,25,50,24,active,'输入窗口')+heatmap(kernels[k],255,83,24,[],'共享卷积核')+heatmap(maps[k],390,50,26,[r*6+c],'特征图：空白未计算',3),600,270),`核${k+1} 位于 (${r},${c})：9对像素与权重相乘求和得到 ${v}；跳帧显示扫描，所有36个位置均实际计算。`,{kernel:k,row:r,column:c,response:v}));}}}const activated=maps.map(m=>m.map(row=>row.map(v=>Math.max(0,v))));frames.push(f(Viz.svg(heatmap(maps[0],90,55,27,[],'卷积响应')+heatmap(activated[0],355,55,27,[],'ReLU：负值归零'),600,260),'ReLU 保留正响应，将负响应归零，引入非线性。',{before:maps[0],after:activated[0]}));const pools=activated.map(m=>seq(3,r=>seq(3,c=>Math.max(m[r*2][c*2],m[r*2][c*2+1],m[r*2+1][c*2],m[r*2+1][c*2+1]))));frames.push(f(Viz.svg(heatmap(activated[1],90,55,27,[],'6×6 特征图')+heatmap(pools[1],365,83,36,[],'3×3 最大池化'),600,265),'每个2×2区域只保留最大响应；压缩空间，也丢失精确位置。',{pooled:pools}));const features=pools.map(m=>sum(m.flat())/9),scores=[features[1]-features[0],3*(features[0]-features[1])],exp=scores.map(v=>Math.exp(v-Math.max(...scores))),probs=exp.map(v=>v/sum(exp));frames.push(f(Viz.bars(features,['核1平均','核2平均']),'把每张池化图的平均值收集为长度2的特征向量。',{features}));frames.push(f(Viz.bars(probs,['类1','类7'],[probs[0]>probs[1]?0:1]),`手工分类头输出：1为${round(probs[0]*100)}%，7为${round(probs[1]*100)}%。${p.digit==='0'?'输入0不在输出类别中，却仍被分配概率；这是范围外输入的反例。':'这组权重没有训练，得分不承诺识别正确；改变笔画比较特征。'}`,{features,scores,probabilities:probs,prediction:probs[0]>probs[1]?1:7}));return{frames};});
}
