/** Editorial descriptions of official course/domain coordinates, not quotations or mastery claims.
 * Bump a node revision on content/kind edits and the graph release on any source change.
 * Stable IDs join this content to the source graph; sourceRefs remain on that graph.
 */
export const OFFICIAL_PATH_CONTENT: Record<string, { kind: 'course' | 'skill_domain'; revision: number; summary: string }> = {
  'digital-literacy': { kind: 'skill_domain', revision: 1, summary: '认识数字设备、常用办公工具与网络信息环境，学习文件管理、信息检索、数据表达和安全使用习惯。通过整理资料与制作数字作品，为后续专业学习建立基本操作能力。' },
  'computer-introduction': { kind: 'course', revision: 1, summary: '从信息表示、算法、计算机系统和软件应用认识计算机科学的主要问题与分支。通过小型计算案例，理解程序、数据和硬件如何协作，并辨认不同专业方向的学习内容。' },
  'computing-ethics': { kind: 'course', revision: 1, summary: '讨论软件和数据应用中的隐私、知识产权、公平性、可访问性与职业责任。能够分析案例中的利益相关者、风险和责任，说明技术方案的社会影响与取舍。' },
  'programming-foundations': { kind: 'course', revision: 1, summary: '学习变量与数据类型、条件与循环、函数和基本输入输出，把简单问题转化为可执行程序。通过阅读、编写和调试小程序，练习分解问题、验证结果和解释代码行为。' },
  'python-programming': { kind: 'course', revision: 1, summary: '使用 Python 的序列、字典、函数、模块和文件处理组织程序，理解异常处理与常用库的基本用法。能够编写数据处理或日常自动化脚本，并为关键逻辑准备可重复的验证样例。' },
  'c-programming': { kind: 'course', revision: 1, summary: '学习 C 语言的数据表示、指针、数组、结构体、内存管理与编译链接过程。通过编写和调试程序理解内存布局与底层执行，识别越界访问、资源泄漏等常见问题。' },
  'calculus': { kind: 'course', revision: 1, summary: '学习极限、导数、积分及多元函数的基本分析方法，理解变化率、累积量与局部近似。能够用微积分描述简单连续模型，为优化、概率和科学计算中的数学推导做准备。' },
  'linear-algebra': { kind: 'course', revision: 1, summary: '学习向量、矩阵、线性方程组、线性变换、特征值与正交分解。能够用矩阵描述数据与变换，解释线性模型的几何意义，为图形计算、机器学习和数值方法建立基础。' },
  'discrete-mathematics': { kind: 'course', revision: 1, summary: '学习逻辑、集合、关系、组合计数、图与递归结构，练习归纳证明和离散建模。能够用形式化语言描述问题，分析简单算法与网络结构中的性质。' },
  'probability-statistics': { kind: 'course', revision: 1, summary: '学习随机变量、常见分布、期望、方差、参数估计与假设检验。能够用样本描述不确定性，解释统计结论的适用条件，避免把相关关系或单次观测当成确定结论。' },
  'linux-fundamentals': { kind: 'course', revision: 1, summary: '熟悉 Linux 文件系统、命令行、权限、进程与基础软件安装，学习管道和简单 Shell 脚本。能够在终端中完成文件操作、运行程序和查看系统状态，为系统管理与开发环境使用做准备。' },
  'web-foundations': { kind: 'course', revision: 1, summary: '理解浏览器、服务器、URL 与 HTTP 的基本协作方式，学习 HTML 结构、CSS 样式和 JavaScript 交互。能够制作简单网页并检查页面、网络请求和脚本运行结果。' },
  'computer-maintenance': { kind: 'course', revision: 1, summary: '识别计算机部件，完成整机装配、系统安装、故障诊断与日常维护。' },
  'windows-server-administration': { kind: 'course', revision: 1, summary: '配置服务器角色、目录与权限、网络服务，并完成基础运行维护。' },
  'network-cabling': { kind: 'course', revision: 1, summary: '完成铜缆与光纤布线设计、端接、测试、验收和工程文档。' },
  'object-oriented-programming': { kind: 'course', revision: 1, summary: '学习类与对象、封装、接口、继承、多态及组合，理解对象职责和协作关系。能够把需求组织成可维护的模块，使用测试检查对象行为，并说明设计选择的影响。' },
  'data-structures': { kind: 'course', revision: 1, summary: '学习数组、链表、栈、队列、树、堆、散列表和图的表示与操作。能够依据访问方式、更新频率和复杂度选择数据结构，实现并验证典型操作。' },
  'digital-logic': { kind: 'course', revision: 1, summary: '学习布尔代数、逻辑门、组合电路、时序电路和有限状态机。能够从逻辑需求设计简单数字电路，分析状态变化、时序约束及电路输出。' },
  'computer-organization': { kind: 'course', revision: 1, summary: '理解指令系统、处理器、存储层次、输入输出与总线如何共同执行程序。能够跟踪简单指令的执行过程，并用数据通路与存储访问解释基本性能差异。' },
  'database-foundations': { kind: 'course', revision: 1, summary: '学习关系表、主外键、基本 SQL 查询与数据增删改，认识约束和事务的作用。能够为小型业务建立数据库、维护数据并完成常见查询，重点是数据库的正确使用。' },
  'networking-foundations': { kind: 'course', revision: 1, summary: '认识网络设备、分层模型、IP 地址、子网、常用协议和基本网络服务。能够配置小型网络并使用诊断命令检查连通性，建立后续网络原理与工程实施的操作基础。' },
  'software-development-foundations': { kind: 'skill_domain', revision: 1, summary: '学习开发环境、版本控制、依赖管理、模块划分和基础测试，理解从源码到可运行程序的过程。能够维护一个小型代码仓库，记录变更并通过测试验证基本功能。' },
  'data-processing': { kind: 'course', revision: 1, summary: '围绕简单数据任务学习采集、清洗、标注、格式转换与质量检查，认识数据使用的来源和权限边界。能够整理可用于分析或模型训练的数据集，并记录处理规则与异常。' },
  'hci-foundations': { kind: 'course', revision: 1, summary: '学习用户研究、交互原型、信息组织、可用性和可访问性，理解界面设计与用户任务的关系。能够设计一个交互流程，通过观察和测试发现使用障碍并提出改进。' },
  'frontend-design-development': { kind: 'course', revision: 1, summary: '从页面结构、样式和交互出发，完成响应式前端与组件化界面开发。' },
  'software-modeling-design': { kind: 'course', revision: 1, summary: '从需求、用例和领域对象出发，使用 UML 与设计模式形成可实现的软件设计。' },
  'system-deployment-operations': { kind: 'skill_domain', revision: 1, summary: '部署应用、数据库与基础网络服务，实施监控、备份、升级和故障处理。' },
  'enterprise-application-development': { kind: 'skill_domain', revision: 1, summary: '用服务端框架、持久化和会话机制实现可部署的企业级业务应用。' },
  'software-testing': { kind: 'course', revision: 1, summary: '设计测试计划与用例，执行功能、性能和自动化测试并形成缺陷报告。' },
  'mobile-cross-platform': { kind: 'course', revision: 1, summary: '使用组件、路由、状态管理和跨平台构建能力交付移动应用。' },
  'mini-program-development': { kind: 'course', revision: 1, summary: '完成小程序页面、数据交互、云端能力接入、测试和发布。' },
  'data-acquisition-technology': { kind: 'course', revision: 1, summary: '针对数据库、日志和互联网数据设计并实施在线或离线采集任务。' },
  'data-preprocessing-etl': { kind: 'course', revision: 1, summary: '识别缺失、重复和不一致数据，完成多源数据抽取、清洗、转换和装载。' },
  'data-analysis-applications': { kind: 'course', revision: 1, summary: '围绕业务指标完成统计分析、批量与实时计算，并撰写分析报告。' },
  'data-visualization-applications': { kind: 'course', revision: 1, summary: '选择合适图表与交互方式，构建可解释的数据展示并输出分析结论。' },
  'big-data-platform-operations': { kind: 'course', revision: 1, summary: '部署和维护分布式存储与计算组件，监测平台运行并处理常见故障。' },
  'algorithms': { kind: 'course', revision: 1, summary: '学习复杂度分析以及分治、贪心、动态规划和图算法等设计方法。能够根据问题约束选择算法、说明正确性，并比较时间与空间开销，而不只复现实现步骤。' },
  'operating-systems': { kind: 'course', revision: 1, summary: '学习进程与线程、调度、同步、虚拟内存、文件系统和设备管理。能够解释操作系统如何分配资源与隔离程序，通过实验分析并发、存储和系统调用行为。' },
  'database-systems': { kind: 'course', revision: 1, summary: '研究数据建模、关系理论、索引、查询执行、事务并发控制和故障恢复。能够分析数据库内部机制，依据一致性与性能需求设计模式、事务和查询方案。' },
  'computer-networks': { kind: 'course', revision: 1, summary: '系统学习分层通信、链路、路由、传输控制与应用协议，分析可靠传输、拥塞和网络性能。能够借助报文与实验解释端到端通信过程，并定位跨层问题。' },
  'software-engineering': { kind: 'course', revision: 1, summary: '学习需求分析、设计、实现、测试、配置管理和软件维护的协作过程。能够围绕真实需求组织迭代交付，形成设计与质量证据，并处理范围、成本与变更之间的取舍。' },
  'theory-of-computation': { kind: 'course', revision: 1, summary: '学习自动机、形式语言、可计算性和复杂性，区分可表达、可求解与高效可求解的问题。通过构造模型和证明理解计算能力的边界，为语言处理与算法研究建立理论基础。' },
  'programming-languages': { kind: 'course', revision: 1, summary: '比较程序语言的语法、语义、类型系统、作用域与求值方式，理解不同编程范式。能够分析语言特性如何影响程序行为，并通过小型解释器或语言实验验证理解。' },
  'computer-security': { kind: 'course', revision: 1, summary: '学习机密性、完整性、可用性、身份认证、访问控制与基础威胁建模。能够识别常见攻击面，说明防护措施的作用和局限，为安全开发与运维建立共同概念。' },
  'web-development': { kind: 'course', revision: 1, summary: '围绕完整 Web 应用学习客户端与服务端协作、路由、数据持久化、认证和部署。能够实现可使用的业务流程，验证接口与页面行为，并处理基本安全和运行问题。' },
  'mobile-development': { kind: 'course', revision: 1, summary: '学习移动应用的界面、生命周期、数据存储、网络访问和设备能力，理解移动端资源与交互约束。能够完成一个应用功能，检查不同运行状态下的行为并准备发布构建。' },
  'network-routing-switching': { kind: 'course', revision: 1, summary: '学习交换、VLAN、路由协议与网络冗余的配置和工作机制。能够按拓扑需求配置交换机与路由器，验证转发路径、隔离策略和故障恢复效果。' },
  'linux-administration': { kind: 'course', revision: 1, summary: '在命令行基础上学习用户与权限、服务管理、存储、网络配置、日志和备份。能够部署与维护 Linux 服务，定位运行故障，并用脚本完成重复管理任务。' },
  'wireless-networking': { kind: 'course', revision: 1, summary: '完成无线局域网勘测、规划、组网、安全配置、管理与优化。' },
  'network-automation': { kind: 'course', revision: 1, summary: '使用脚本、接口和配置管理工具批量实施网络配置、巡检和变更。' },
  'network-virtualization': { kind: 'course', revision: 1, summary: '理解虚拟交换、网络隔离、隧道和软件定义网络，并完成基础部署。' },
  'network-systems-integration': { kind: 'course', revision: 1, summary: '完成需求分析、拓扑与布线设计、设备选型、实施、测试和工程验收。' },
  'computer-graphics': { kind: 'course', revision: 1, summary: '学习几何表示、坐标变换、投影、光照、纹理与渲染流程。能够实现或使用基本图形算法生成二维、三维画面，并分析画面质量与计算开销。' },
  'embedded-systems': { kind: 'course', revision: 1, summary: '学习嵌入式处理器、外设接口、中断、定时和实时任务组织，理解软硬件协同。能够完成传感器读取或设备控制程序，并检查时序、资源和可靠性约束。' },
  'artificial-intelligence': { kind: 'course', revision: 1, summary: '认识搜索、知识表示、推理、规划与机器学习等人工智能方法。能够为简单问题选择建模与求解方式，比较规则和数据方法的适用条件，并讨论系统局限。' },
  'machine-learning': { kind: 'course', revision: 1, summary: '学习监督与无监督学习、特征、损失函数、训练验证划分和泛化评估。能够建立分类、回归或聚类基线，识别过拟合与数据泄漏，并用合适指标比较模型。' },
  'data-mining': { kind: 'course', revision: 1, summary: '围绕从数据发现模式学习关联分析、聚类、分类与异常检测等方法。能够将业务问题转为分析任务，评估模式的有效性，解释发现结果及其适用范围。' },
  'distributed-systems': { kind: 'course', revision: 1, summary: '研究多节点通信、复制、一致性、故障、共识与分布式存储。能够分析网络延迟和部分失败下的系统行为，设计简单分布式服务并解释可用性与一致性的取舍。' },
  'cloud-computing': { kind: 'course', revision: 1, summary: '学习云服务模型、资源虚拟化、弹性、存储、网络与服务管理。能够为应用选择云资源和部署方式，比较容量、成本、可用性与运维责任。' },
  'virtualization-technology': { kind: 'course', revision: 1, summary: '理解计算、存储与网络虚拟化，创建和管理虚拟机、镜像与资源池。' },
  'cloud-platform-operations': { kind: 'course', revision: 1, summary: '规划并运维私有云和公有云中的计算、网络、存储、数据库与监控服务。' },
  'container-cloud-operations': { kind: 'course', revision: 1, summary: '管理镜像、容器网络、存储、编排、监控和应用发布。' },
  'cloud-security-applications': { kind: 'course', revision: 1, summary: '配置身份认证、云扫描、防护、监控与安全运营能力，保护云平台和云服务。' },
  'devops': { kind: 'skill_domain', revision: 1, summary: '学习版本协作、自动构建与测试、制品管理、环境配置和持续交付。能够建立可重复的交付流水线，验证发布结果，并设计回退与运行反馈机制。' },
  'compilers': { kind: 'course', revision: 1, summary: '学习词法和语法分析、语义检查、中间表示、代码生成与基本优化。能够实现简单语言的编译流程，解释源程序到目标代码的转换及错误定位。' },
  'parallel-computing': { kind: 'course', revision: 1, summary: '学习任务与数据并行、共享内存与消息传递、同步及负载均衡。能够分解计算任务、实现并行程序，并通过加速比、开销和资源使用评估效果。' },
  'cybersecurity-engineering': { kind: 'course', revision: 1, summary: '把威胁分析、防护部署、访问控制、监测和验证组织为网络安全工程方案。能够依据网络与业务边界实施安全措施，记录配置、验证结果与剩余风险。' },
  'web-security': { kind: 'course', revision: 1, summary: '分析 Web 应用中的认证、授权、输入处理、会话和浏览器安全边界。能够在授权测试环境中识别典型漏洞、修复成因并通过回归测试验证防护效果。' },
  'operating-system-security': { kind: 'course', revision: 1, summary: '检查账户、权限、文件系统和服务配置，实施主流操作系统安全加固。' },
  'security-product-configuration': { kind: 'course', revision: 1, summary: '部署和管理防火墙、入侵检测、漏洞扫描、安全审计等防护产品。' },
  'storage-disaster-recovery': { kind: 'course', revision: 1, summary: '设计存储、备份与 RAID 方案，实施数据恢复和信息系统容灾。' },
  'digital-forensics': { kind: 'course', revision: 1, summary: '依法获取、固定、恢复和分析电子数据，形成可检查的取证过程与结果。' },
  'security-risk-assessment': { kind: 'course', revision: 1, summary: '识别资产、威胁与脆弱性，完成主机、网络、应用和数据安全评估报告。' },
  'applied-cryptography': { kind: 'course', revision: 1, summary: '学习对称加密、公钥密码、摘要、消息认证、数字签名与密钥管理的目标和基本机制。能够解释密码协议提供的保证，正确选择成熟组件并识别误用风险。' },
  'data-engineering': { kind: 'course', revision: 1, summary: '学习数据管道、存储模型、批处理与流处理、调度、质量检查和血缘管理。能够设计可重复的数据流，处理失败、重复与模式变化，为分析和应用提供可靠数据。' },
  'software-architecture': { kind: 'course', revision: 1, summary: '学习模块与服务划分、接口、数据流和常见架构风格，围绕可用性、性能、安全与可维护性分析质量需求。能够表达系统结构、记录架构决策并验证关键取舍。' },
  'optimization': { kind: 'course', revision: 1, summary: '学习目标函数、约束、梯度方法和凸优化的基本概念，理解最优条件与收敛行为。能够建立简单优化模型，选择求解方法并分析解的质量与数值稳定性。' },
  'statistical-learning': { kind: 'course', revision: 1, summary: '研究经验风险、模型复杂度、泛化误差、正则化和学习问题的统计假设。能够解释训练效果与泛化能力之间的关系，并分析理论结论的条件与限制。' },
  'deep-learning': { kind: 'course', revision: 1, summary: '学习神经网络、反向传播、优化、正则化及常用网络结构。能够实现训练与验证流程，诊断收敛和过拟合问题，并依据任务与资源选择模型。' },
  'computer-vision': { kind: 'course', revision: 1, summary: '学习图像表示、特征与视觉模型，处理分类、检测、分割等典型任务。能够准备视觉数据、训练或调用模型，并分析光照、视角与数据分布变化对结果的影响。' },
  'natural-language-processing': { kind: 'course', revision: 1, summary: '学习文本表示、语言建模及分类、序列标注、理解和生成任务。能够构建语言处理流程，选择数据与评价方法，并分析歧义、偏差与生成错误。' },
  'reinforcement-learning': { kind: 'course', revision: 1, summary: '学习状态、动作、奖励、策略、价值函数及探索与利用，理解序贯决策的建模方式。能够在受控环境中训练和评估策略，分析奖励设计、样本效率和训练稳定性。' },
  'robotics': { kind: 'course', revision: 1, summary: '学习机器人坐标与运动学、感知、定位、路径规划和反馈控制。能够把传感、决策与执行组织成基本闭环，通过仿真或实验验证运动任务与安全约束。' },
  'mlops': { kind: 'skill_domain', revision: 1, summary: '学习模型与数据版本、训练流水线、部署、在线监测和再训练管理。能够把模型转为可运行服务，检查性能、数据漂移与服务质量，并形成可追溯的发布和回退过程。' },
  'llm-foundations': { kind: 'course', revision: 1, summary: '学习分词、嵌入、注意力、Transformer、预训练与后训练的基本机制，理解上下文与推理过程。能够分析大语言模型的能力、资源约束和常见失效，为检索增强与智能体应用建立基础。' },
  'ai-safety-ethics': { kind: 'course', revision: 1, summary: '分析 AI 系统的可靠性、隐私、公平性、滥用与治理问题，区分模型、应用和组织层面的责任。能够为具体场景提出风险评估、验证和持续监测方案，并说明其局限。' },
  'advanced-algorithms': { kind: 'course', revision: 1, summary: '在基础算法上研究随机化、近似、复杂性与更深入的图和组合算法。能够阅读算法论证、构造正确性与复杂度证明，并比较不同计算假设下的求解方案。' },
  'advanced-systems': { kind: 'skill_domain', revision: 1, summary: '围绕现代操作系统、分布式存储与大规模计算研读系统论文和实现。能够复现或设计系统实验，分析一致性、隔离、调度与性能决策，并解释实验结论的边界。' },
  'formal-methods': { kind: 'course', revision: 1, summary: '学习规格描述、不变式、模型检测与程序验证，把系统性质转化为可检查的形式化要求。能够对小型程序或协议建立模型，解释证明、反例及建模假设。' },
  'security-operations': { kind: 'course', revision: 1, summary: '学习安全告警分析、事件分级、遏制、恢复与复盘，组织日志和取证信息形成事件时间线。能够在授权演练中处理安全事件、记录决策与证据，并提出后续防护改进。' },
  'engineering-debugging-observability': { kind: 'skill_domain', revision: 1, summary: '系统学习复现、假设、定位和验证故障，并使用日志、指标、追踪与剖析建立可解释的运行证据，最终能够完成一次有依据的故障归因。' },
  'api-design-evolution': { kind: 'skill_domain', revision: 1, summary: '围绕接口契约、错误模型、兼容性、版本、幂等与弃用策略设计可长期演进的服务边界，并通过契约测试验证调用方和服务方的共同预期。' },
  'software-maintenance-evolution': { kind: 'skill_domain', revision: 1, summary: '阅读既有系统，安全重构与迁移，管理依赖和技术债，并用回归证据控制长期变更风险，能够为一次真实演化说明边界、迁移步骤和回退策略。' },
  'open-source-collaboration': { kind: 'skill_domain', revision: 1, summary: '通过问题描述、提交、代码评审、文档、许可证和社区协作完成可被他人检查与接续的工程贡献，并理解维护者、贡献者与用户之间的责任边界。' },
  'performance-engineering': { kind: 'skill_domain', revision: 1, summary: '从工作负载与服务目标出发测量延迟、吞吐和资源成本，使用剖析、基准和容量模型定位瓶颈，并验证优化是否改善真实负载而非单一样例。' },
  'reliability-incident-response': { kind: 'skill_domain', revision: 1, summary: '定义服务目标和错误预算，设计降级与恢复机制，并通过值守、事件指挥和无责复盘改善真实生产系统。' },
  'secure-software-supply-chain': { kind: 'skill_domain', revision: 1, summary: '把威胁建模、安全编码、依赖与构建来源、制品签名、漏洞响应嵌入软件全生命周期，并以可追溯清单和验证流程降低交付风险。' },
  'information-retrieval': { kind: 'course', revision: 1, summary: '学习索引、召回与排序、相关性判断、离线评测和交互反馈，理解从关键词检索到语义检索的共同骨架。' },
  'data-governance-privacy': { kind: 'skill_domain', revision: 1, summary: '管理数据质量、目录、血缘、访问、保留与删除，并把隐私风险和合规约束转化为可验证的工程控制。' },
  'ai-system-evaluation': { kind: 'skill_domain', revision: 1, summary: '从任务定义、数据切分、指标、基线和不确定性出发评估模型与智能体，并检查鲁棒性、安全性和真实使用效果。' },
  'platform-engineering': { kind: 'skill_domain', revision: 1, summary: '把基础设施、交付、可观测性和安全能力组织成自助式开发者平台，以产品思维降低团队认知负担，并用内部用户反馈和交付指标持续验证平台价值。' },
  'numerical-scientific-computing': { kind: 'course', revision: 1, summary: '研究浮点误差、数值稳定性、线性方程与迭代方法，并用向量化、误差分析和对照实验验证计算结果是否可靠、可复现。' },
  'research-methods': { kind: 'course', revision: 1, summary: '学习研究问题界定、文献检索与评述、假设、实验设计、结果分析和学术表达。能够制定可验证的研究计划，维护可复现记录，并区分已有结论、推测与自身贡献。' },
  'retrieval-augmented-generation': { kind: 'course', revision: 1, summary: '学习文档处理、分块与索引、召回与重排、上下文组织和有依据的生成。能够构建检索增强问答流程，分别评估检索与回答质量，定位遗漏证据、错误引用和知识过期问题。' },
  'agent-engineering': { kind: 'skill_domain', revision: 1, summary: '围绕模型调用、工具、上下文、状态与记忆、工作流编排和评测构建 AI 智能体。能够交付一个有明确权限、失败恢复与停止条件的应用，并用真实任务检查工具执行和用户体验。' },
  'multi-agent-systems': { kind: 'course', revision: 1, summary: '研究多个智能体之间的角色分工、通信、协调、共享状态与冲突处理。能够设计并评估协作流程，比较其与单智能体方案的效果、成本及错误传播，明确交接和停止条件。' },
  'capstone-project': { kind: 'course', revision: 1, summary: '围绕真实需求综合运用分析、设计、实现、测试和交付方法，完成可演示、可验收的工程作品。通过需求记录、版本历史、测试和复盘说明个人贡献与方案取舍。' },
  'thesis-research': { kind: 'course', revision: 1, summary: '围绕明确研究问题组织文献、方法、实验和论证，形成符合学术规范的研究成果。能够说明贡献、有效性威胁与局限，提交可检查的论文及必要的复现材料。' },
}
